version: '3.9'

services:
  tryout.ui:
    build: ./TRYOUT.UI
    ports:
      - "4200:80"
  tryout:
    build: ./TRYOUT
    ports:
      - "5000:80"
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./htpasswd:/etc/nginx/htpasswd
    depends_on:
      - tryout.ui
volumes:
  htpasswd:
